name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: rust
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo fmt --all -- --check
        if: ${{ steps.release.outputs.release_created }}
      - run: cargo install wasm-pack
        if: ${{ steps.release.outputs.release_created }}
      - run: wasm-pack build
        if: ${{ steps.release.outputs.release_created }}
      - run: wasm-pack pack
        if: ${{ steps.release.outputs.release_created }}
      - uses: oven-sh/setup-bun@v1
        if: ${{ steps.release.outputs.release_created }}
      - run: bun rename
        if: ${{ steps.release.outputs.release_created }}
      - run: wasm-pack publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
